org: danielferguson
app: floodmap
service: api
frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-domain-manager

useDotenv: true
configValidationMode: error

custom:
  customDomain:
    domainName: api.floodmap.app
    securityPolicy: tls_1_2
    endpointType: REGIONAL
    createRoute53Record: true
    certificateArn: arn:aws:acm:ap-southeast-2:291736510642:certificate/f170b093-8d9b-4674-8072-683aff606900
    apiType: rest
    autoDomain: true

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-2
  memorySize: 512
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    AUTH0_CLIENT_PUBLIC_KEY: ${file(./public_key.pem)}

functions:
  getHazards:
    handler: handlers/getHazards.handler
    events:
      - http:
          method: GET
          path: /hazards
          cors:
            origin: "https://www.floodmap.app"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true
  createHazard:
    handler: handlers/createHazards.handler
    events:
      - http:
          method: POST
          path: /hazards
          cors:
            origin: "https://www.floodmap.app"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true

# only include the Prisma binary required on AWS Lambda while packaging
package:
  patterns:
    - "!node_modules/.prisma/client/libquery_engine-*"
    - "node_modules/.prisma/client/libquery_engine-rhel-*"
    - "!node_modules/prisma/libquery_engine-*"
    - "!node_modules/@prisma/engines/**"
