name: Deploy Serverless API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Node packages
        run: |
          npm ci
          npm i -g serverless@3.x
      - name: Setup Serverless credentials
        run: |
          serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy Serverless project
        run: serverless deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
