name: Deploy Serverless API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Node packages
        run: |
          npm ci
          npm i serverless@3.x
